# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fe63acbe7ec65ffc8f31cd0626af6a9b4e8f314792aee88bb336b06b8efde5c67ffb06259a74edc5e06d560c2a9946b282b96e2eecbb936d0c452fd2b50cc03

test:
  secret_key_base: 59b287d86a67258264303b70c6065fe3ca23f8cd4b4b61e2fcfc61c32c073ea836bc6c184ba47f615854d68b310ad9404a3a8fa6cc5a38add37adadc3e57802e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
